### ISSUE TITLE
Problem with initiate the generator 

### ISSUE THREAD

**Issue by oleg-demkovych** [hung-phan/generator-rails-react-webpack#10]
Have some issue when initiate YO generator: 

> An error occurred while installing did_you_mean (1.0.0), and Bundler cannot
> continue.
> Make sure that `gem install did_you_mean -v '1.0.0'` succeeds before bundling.
> Processing Bowerfile
> /Users/denys/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/resolver.rb:354:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'bootstrap-sass' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
>     from /Users/denys/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/resolver.rb:330:in`each'
>     from /Users/denys/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/resolver.rb:330:in `verify_gemfile_dependencies_are_found!'
>     from /Users/denys/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/resolver.rb:199:in`start'
>     from /Users/denys/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/resolver.rb:183:in `resolve'
>     from /Users/denys/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/definition.rb:198:in`resolve'
>     from /Users/denys/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
>     from /Users/denys/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in`specs_for'
>     from /Users/denys/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
>     from /Users/denys/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in`requested_specs'
>     from /Users/denys/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
>     from /Users/denys/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler.rb:92:in`setup'
>     from /Users/denys/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'
>     from /Users/denys/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in`require'
>     from /Users/denys/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
>     from /Users/denys/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in`require'
>     from /Users/denys/Desktop/dev/app-name/config/boot.rb:3:in `<top (required)>'
>     from bin/rails:3:in`require_relative'
>     from bin/rails:3:in `<main>'
> identical tmp/yeoman/Bowerfile
> fs.js:549
>   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
> Error: ENOENT: no such file or directory, open '/Users/denys/Desktop/dev/app-name/Bowerfile'
>     at Error (native)
>     at Object.fs.openSync (fs.js:549:18)
>     at Object.fs.readFileSync (fs.js:397:15)
>     at readFileAsString (/usr/local/lib/node_modules/generator-rails-react-webpack/node_modules/yeoman-generator/lib/actions/wiring.js:275:13)
>     at module.exports.yeoman.generators.Base.extend.bower (/usr/local/lib/node_modules/generator-rails-react-webpack/app/index.js:135:23)
>     at /usr/local/lib/node_modules/generator-rails-react-webpack/node_modules/yeoman-generator/lib/base.js:341:43
>     at /usr/local/lib/node_modules/generator-rails-react-webpack/node_modules/async/lib/async.js:551:21
>     at /usr/local/lib/node_modules/generator-rails-react-webpack/node_modules/async/lib/async.js:227:13
>     at iterate (/usr/local/lib/node_modules/generator-rails-react-webpack/node_modules/async/lib/async.js:134:13)
>     at /usr/local/lib/node_modules/generator-rails-react-webpack/node_modules/async/lib/async.js:145:25

**Comment by hung-phan** [comment]
I was kind of busy these days, will fix at the weekend. :smile:

**Comment by hung-phan** [comment]
Hi @olegdemkovych, this is the README from `https://github.com/yuki24/did_you_mean` `Ruby 2.3 ships with this gem and it will automatically be required when a Ruby process starts up. No special setup is required.`. I try to install gem with ruby 2.3.0 and it works fine for me (I use rbenv to install fyi). I can confirm with you version 2.2.1 will not work, the way to solve it could be remove gem 'did_you_mean` from Gemfile.

**Comment by hung-phan** [comment]
https://github.com/hung-phan/generator-rails-react-webpack/issues/11
