### ISSUE TITLE
Gulp-LiveReload x Guard

### ISSUE THREAD

**Issue by jonathan-soifer** [hung-phan/generator-rails-react-webpack#9]
Hi,

Have you ever considered using Gulp in this Workflow? Is there any obvious reason why you wouldn't?

**Comment by hung-phan** [comment]
I have gulp in this workflow, see gulpfile.js. Maybe, it is not what you expect like css preprocessor, for example.

**Comment by jonathan-soifer** [comment]
Sorry, I meant using Gulp-LiveReload as opposed to Guard.

**Comment by hung-phan** [comment]
Yes, could be an option. But I already rely on webpack for its [hot module replacement](http://webpack.github.io/docs/hot-module-replacement-with-webpack.html) for js code. Yes, there are still limitations with the css. Currently, I use the guard for the css only, if that what you mean.

**Comment by jonathan-soifer** [comment]
Yup, thank you for your time!
I'll be joining the hundreds (thousands?) of users :+1:
